### ISSUE TITLE
[Ready To Test]

### ISSUE THREAD

**Issue by calippo** [buildo/retro#45]
## sub-issues

- [x] Collect endpoints automatically #46 
~~- [ ] Add errors handling #47~~
- [x] Implement sbt plugin #59 **[calippo]**
- [x] Add errors handling #48 **[calippo]**

**Comment by kanbanbot** [comment]
@tpetrucciani cambiare card? @calippo intervieni anche tu?

**Comment by tpetrucciani** [comment]
@calippo c'è un po' di confusione sugli issue in questa macro, adesso l'unica aperta dovrebbe essere #47 "Add auth poc" (che però sopra è segnata come "Add errors handling")

non so quanto senso abbia che continui a stare nella macro

magari chiudiamo la macro e rendiamo quella un issue a parte?

(poi ci sono già gli altri issue non nella macro che invece sono descritti e organizzati meglio)

**Comment by calippo** [comment]
Sì, chiudiamo questa macro per l'amor del cielo

**Comment by tpetrucciani** [comment]
Chiudo questa, lasciando aperto invece l'unico sub-issue rimastro
